# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
google_tags: GTM-5HVW522
youtube_username: kiyamelak
# {% if site.google_analytics and jekyll.environment == 'production' %}
# {% include analytics.html %}
# {% endif %}
title: Kirubel Tadesse
first_name: Kirubel
last_name: Tadesse
email: kiyamelak@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am interested in data science, swarm robotics, and deep learning. Master's focus area is Computer Engineering. I am currently working on topics like Artificial Intelligence (AI), Deep Learning, Machine Language, and neural networks (CNN, RNN, and MLP) about irrigation models.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# jekyll_analytics:
#   GoogleAnalytics: # Add, if you want to track with Google Analytics
#     id: UA-150915906-1 # Required - replace with your tracking id
#     anonymizeIp: false # Optional - Default: false - set to true for anonymized tracking

#  Matomo:                   # Add, if you want to track with Matomo (former Piwik Analytics)
#    url: https://kirubeltadesse.github.io/ # Required - url to Matomo installation without trailing /
#    siteId: "G-DD12MSVZTZ"          # Required - replace with your Matomo site id (Write id as string)
#
#  Piwik:                    # Add, if you want to track with Piwik
#    url: piwik.example.com  # Required - url to Piwik installation without trailing /
#    siteId: "1234"          # Required - replace with your Piwik site id (Write id as string)

#  MPulse:                   # Add if you want to track performance with mPulse
#    apikey: XXXXX-YYYYY-ZZZZZ-AAAAA-23456   # Required - replace with your mPulse API key
# Google Analytics

# Build settings
# sass:
#   sass_dir: _sass
# include: ["resume"]
# markdown: kramdown
# kramdown:
#   input: GFM
# theme: minima #jekyll-theme-cayman #jekyll-theme-minimal
# plugins:
#   - jekyll-feed
#   - jekyll-analytics
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

footer_text: >
  <p>I am interested in data science, artificial Intelligence, and swarmie robotics. I am currently actively participating in AI topics. If you are interested, please reach out</p>

# url:  # the base hostname & protocol for your site
# baseurl: /al-folio # the subpath of your site, e.g. /blog/
last_updated: false # set to true if you want to display last updated in the footer

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: false

# Dimensions
max_width: 800px

# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

twitter_username: kirubelmel
github_username: kirubeltadesse
linkedin_username: kirubeltadesse
stackoverflow_username: 4990583/kirubel-tadesse
# scholar_userid: # your Google Scholar ID
# orcid_id: # your ORCID ID
medium_username: kiyamelak
# quora_username: # your Quora username
# publons_id: # your ID on Publons
# research_gate_profile: # your profile on ResearchGate
# blogger_url: # your blogger URL
# keybase_username: # your keybase user name

contact_note: >
  You can even add a little note about which of these is the best way to reach you.
#     id: UA-150915906-1 # Required - replace with your tracking id
# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: kirubeltadesse # your blog must have a name for it to show up in the nav bar
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/

# Pagination
pagination:
  enabled: true
  paginate: 5
  paginate_path: "/blog/page:num"

# Comments
disqus_shortname: kiya # put your disqus shortname

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages"]
exclude: [vendor]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-twitter-plugin
  - jemoji
  # - bootstrap
  # - material-sass

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: Tadesse
  first_name: [Kirubet, M.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_tags: false
enable_mansory: true
enable_math: false
enable_tooltips: true
enable_darkmode: true
show_social_icons: true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.0"
  integrity: "sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg=="
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.1.2"
mansory:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha512-hj9rznBPdFg9A4fACbJcp4ttzdinMDtPrtZ3gBD11DiY3O1xJfn0r1U5so/J0zwfGOzq9teIaH5rFmjFAFw8SA=="
    js: "sha512-XFd1m0eHgU1F05yOmuzEklFHtiacLVbtdBufAyZwFR0zfcq7vc6iJuxerGPyVFOXlPGgM8Uhem9gwzMI8SJ5uw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
