project:
  type: website
  output-dir: _site

website:
  title: "Kirubel Tadesse"
  site-url: "https://kirubeltadesse.github.io"
  description: "I am interested in data science, artificial intelligence, and swarm robotics. Master's focus area is Computer Engineering."
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog/index.qmd
      - text: "Projects"
        href: /projects/
      - text: "Resume"
        href: /resume/
    right:
      - icon: github
        href: https://github.com/kirubeltadesse
      - icon: twitter
        href: https://twitter.com/kirubelmel
      - icon: linkedin
        href: https://linkedin.com/in/kirubeltadesse

  page-footer:
    left: "© 2024 Kirubel Tadesse"
    right: 
      - icon: github
        href: https://github.com/kirubeltadesse
      - icon: twitter  
        href: https://twitter.com/kirubelmel

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    toc-location: right
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto