<<<<<<< HEAD
version: '3'
=======
version: "3"
>>>>>>> zcal

services:
  jekyll-services:
    image: jekyll/jekyll:4.0
    volumes:
      - ./:/srv/jekyll
<<<<<<< HEAD

    ports:
      - 4000:4000
    command: 'jekyll serve'
=======
      - .:/workspace:cached
    ports:
      - 4000:4000
    command: "jekyll serve"
>>>>>>> zcal
